### ISSUE TITLE
[improvement] Move celery tasks to it's specific API container

### ISSUE THREAD

**Issue by atb00ker** [openwisp/docker-openwisp#112]
I was initially mistaken that the celery tasks need to be in the same container where celery is running, this might not be the case and we can move the task to it's specific container.

https://github.com/openwisp/docker-openwisp/blob/master/build/common/openwisp/celery.py

Example:

```
    radius_schedule = {
        'radius-periodic-tasks': {
            'task': 'openwisp.tasks.radius_tasks',
            'schedule': crontab(minute=30, hour=3),
            'args': ()
        },
    }
```

Can be moved to `openwisp-radius` container.

P.S: This task may remove the requirement of `SET_TOPOLOGY_TASKS` & `SET_RADIUS_TASKS`, hence these variables shall be removed with their mention in `docs/ENV.md` file and [README.md](https://github.com/openwisp/docker-openwisp#disabling-services) file.

**Comment by nepython** [comment]
@atb00ker,if I understood the title correctly, it is required to create a new **API** container(since I didn't find any currently existing) and move the tasks(which are currently in celery) to them.
Though, was a bit confused as in the comment below it is stated,
>move the task to it's specific container.

This implies, I guess moving the tasks to openwisp_radius and openwisp_topology container.
So, can you please specify which of the above has been implied here(and please correct me incase I am wrong in both instances) :blush:

**Comment by atb00ker** [comment]
Sorry for the confusion, Your second understanding(` guess moving the tasks to openwisp_radius and openwisp_topology container.`) is correct. I tried to make it more clear, please let me know if there is still a question with it! :smile:

**Comment by nepython** [comment]
Thanks for the quick response, shall I take this issue, I will try to complete it asap after I finish the current one.

**Comment by nemesisdesign** [comment]
Can this be closed? I think so.

**Comment by atb00ker** [comment]
Yep, can be closed, closing: https://github.com/openwisp/docker-openwisp/pull/208
