### ISSUE TITLE
Using my own reverse proxy

### ISSUE THREAD

**Issue by SoulEater45** [openwisp/docker-openwisp#122]
I switched from Nginx to Traefik quite some time ago and wanted to run openwisp on that server.
Sadly I am not able to access the dashboard using my own reverse proxy, so I wanted to ask if it is possible to even to use my own proxy.
Thanks in advance!

**Comment by atb00ker** [comment]
Hi @SoulEater45 

I have never used traefik, so I don't know much about it but docker-openwisp is designed to be configurable, so it should work.

However, I can say a change like that wouldn't work out of the box, it may require some effort to remove nginx and ensure everything is working. You need to have similar [configurations as openwisp-nginx](https://github.com/openwisp/docker-openwisp/tree/master/build/openwisp_nginx).

1. dashboard, controller, radius, network topology & websocket containers are running django with uwsgi and each one of them need a reverse proxy infront of them to communicate with the outside world.
2. To avoid sending all the traffic through the internet, there are some internal domains (XYZ.internal) used as well, so you'll need to replicate that.

My advice would be, start a local instance of docker-openwisp on your machine: `docker-compose run nginx sh` and look at the final configurations instead of the templates; that should be helpful.

As far as containers like openwisp-dashboard are concerned, they don't care what's the reverse proxy, they are listening for connections on their port and are not coupled with nginx.

P.S: I am closing this as this is our bug tracker and this issue is for support, please ask further support questions on the mailing list: https://groups.google.com/g/openwisp


Thanks, 
Ajay Tripathi
