### ISSUE TITLE
Control versioning of container images

### ISSUE THREAD

**Issue by replicajune** [openwisp/docker-openwisp#125]
## Issue description

Currently when containers are built, they're sourced from the openwisp account in docker hub. the base images sourced that way all have "latest" as version value, and docker hub don't have any fixed version for any of the openwisp images.

## expected behavior

We should be able to deploy the openwisp stack with fixed version for openwisp components so multiple deployement would lead to the exact same deployed application

## current behavior

deployed stack is dependent on the latest time an image was build in docker hub, version may change

## proposed fix approach

All images should be sourced with a fixed version according to the least stable openwisp release so all images would be referenced with the openwisp version 0.7.0 for exemple. Alternatively if some components have asynchronious release planning,  then each openwisp release should be able to refer to tested version which the openwisp would be stable and tested for.

For exemple (maybe a bad one because of the compexity of the support matrix, sorry for that) the hortonwork hadoop distribution has a matrix to show which version of the distribution is compatible with which components (see supportmatrix.hortonworks.com).

**Comment by atb00ker** [comment]
Hi,

Thanks for opening the issue. 
Currently, docker-openwisp is not released and is under development, hence there is no version available on the docker-hub.
Currently, `latest` points to `alpha.1` which is the last well tested working set of images and can be used for locking the version for now. (since it's not release, stability of the same cannot be guaranteed but it has been working fine for me so far)

When a stable version of the images is ready, I'll tag it appropriately.
 
I like your suggestion of support matrix. I would surely add it with the first stable release!

**Comment by replicajune** [comment]
that sounds good @atb00ker, I appreciate the anwsers, thank you :+1:

**Comment by atb00ker** [comment]
Hi,

Added the version table here: https://github.com/openwisp/docker-openwisp#available-images
You can checkout the images here: https://gitlab.com/openwisp/docker-openwisp/container_registry

Closing this issue, please reopen for any further discussion! :smile:

**Comment by replicajune** [comment]
This is awsome, thanks a lot @atb00ker !!
