### ISSUE TITLE
Question - Why does the project not use standard deployment structure?

### ISSUE THREAD

**Issue by focher** [openwisp/docker-openwisp#289]
Hi, as I've tried to get this project running I'm a bit curious as to how the project is designed. I run a number of containers from publicly published Docker images. In every instance, the publisher provides a docker-compose.yml, and maybe an .env configuration (but those environment variables are usually embedded directly in the docker-compose.yml). 

This project seems to have been built with a lot of requirements that don't seem necessary, so I'm curious why?

1. Ubuntu / Debian as the host system is a requirement.
2. The setup script requires that it installs Docker, and fails if it can't (without even checking if Docker is already on the host).

I really appreciate the project, but as I'm trying to host the environment on a non Ubuntu / Debian machine all the dependencies / assumptions / requirements are requiring me to do a lot of workarounds.

I hope my questions don't offend anyone, as maybe I am ignorant as to evolving best practices.

**Comment by atb00ker** [comment]
1. If I remember correctly, "Ubuntu / Debian" requirement is only for using auto-install script.
2. Again, auto-install script tries to install docker. (However, it ideally shouldn't fail if docker is available.)

It's been a very long time since I have updated / checked that script.
You can also simply use `docker-compose.yml` with `.env` file.

Checkout: https://github.com/openwisp/docker-openwisp/blob/master/docs/QUICK_SETUP.md
(You don't even need to use the makefile, `docker-compose up -d` should do the trick.)

That said, remember the official method to install openwisp is still using ansible-openwisp, I worked on this project and lately I haven't even it any attention: https://github.com/openwisp/ansible-openwisp2

**Comment by focher** [comment]
Thank you very much for the explanation. I’ll investigate ansible-openwisp.
