### ISSUE TITLE
run openwisp-radius periodic tasks

### ISSUE THREAD

**Issue by atb00ker** [openwisp/docker-openwisp#50]
Some tasks need to run perodically for openwisp-radius which are currently not in a cronjob.
A celery-beat instance or a kubernetes's cronjob object needs to be implemented for this!

**Comment by nemesisdesign** [comment]
celery beat could run the same configuration of celery, but would be another container which would not do much, except telling the worker containers, which may be multiple containers, what to do and when, while the celery beat container would be always only 1.

The problem is that not only we need to do this work on the docker-openwisp side, we may need to add the celery tasks for the management commands we used to run in a cronjob, which may slow us down here. In order to avoid that, maybe now you could define the celery task somewhere here, like a project wide celery task definition, in which you would just define some tasks using the `@shared_task` decorator, one task for each management command defined here:

https://django-freeradius.readthedocs.io/en/latest/general/management_commands.html

Can you please make the arguments configurable via env vars?

**Comment by nemesisdesign** [comment]
PS: these should be run once a day in the early morning, all of them

**Comment by atb00ker** [comment]
Closed by #60
